### ISSUE TITLE
Lock not being detected. "Total August Locks Found: undefined" "TypeError: deviceLists.map is not a function"

### ISSUE THREAD

**Issue by hrhnick** [homebridge-plugins/homebridge-august#1]
### Current Situation

- Installed latest beta to test api based events; homebridge-august v0.1.0-beta.18
- Plugin appeared to authenticate as 2FA code was received and added to plugin config.
- August WiFi Smart Lock (Gen 4) does not appear in accessories within Homebridge.
- Attempted both directly connected to WiFi, and connected via August Bridge (preferred to save battery life.)
- Lock does not appear in either WiFi setup method. (Works via August app and other Homebridge August plugins.)

### Logs

```markdown
[10/6/2022, 9:31:08 PM] [August] Total August Locks Found: undefined
[10/6/2022, 9:31:08 PM] [August] TypeError: deviceLists.map is not a function
```

### Configuration

```json
{
            "name": "August",
            "credentials": {
                "augustId": "xxxxxxx@xxxxx.com",
                "password": "xxxxxxxxx",
                "validateCode": "xxxxxxx",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "August"
        },
```

### Environment

- OS: Ubuntu Focal Fossa (20.04.4 LTS)
- Software: https://github.com/oznu/docker-homebridge
- Node: v16.17.1
- npm: 8.5.0

**Comment by donavanbecker** [comment]
can you try latest beta? also please clear out validateCode after installing and get new code.

**Comment by hrhnick** [comment]
- Upgraded to beta 22.
- Cleared out code and entered new one.
- Still get "[10/6/2022, 10:17:45 PM] [August] TypeError: deviceLists.map is not a function" and no locks listed.

**Comment by donavanbecker** [comment]
can you get me debug logs?

**Comment by hrhnick** [comment]
```
[10/6/2022, 10:18:41 PM] ---
[10/6/2022, 10:18:42 PM] Loaded plugin: homebridge-august@0.1.0-beta.22
[10/6/2022, 10:18:42 PM] Registering platform 'homebridge-august.August'
[10/6/2022, 10:18:42 PM] ---
[10/6/2022, 10:18:44 PM] [August] Initializing August platform...
[10/6/2022, 10:18:44 PM] [August] Using Config Logging: debug
[10/6/2022, 10:18:44 PM] [August] [DEBUG] Finished initializing platform: August
[10/6/2022, 10:18:44 PM] [August] Platform Config: {"logging":"debug","refreshRate":[Undefined],"pushRate":[Undefined]}
[10/6/2022, 10:18:44 PM] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[10/6/2022, 10:18:44 PM] [August] [DEBUG] Config OK
[10/6/2022, 10:18:44 PM] [August] [DEBUG] Executed didFinishLaunching callback
[10/6/2022, 10:18:44 PM] [August] [DEBUG] {"config":{"apiKey":"xxxxxxxxx","pnSubKey":"xxxxxxxxx","installId":"xxxxxxxxxxxx","idType":"email","augustId":"xxxxx@xxxxxx","password":"xxxxxxxxx"}}
[10/6/2022, 10:18:45 PM] [August] Total August Locks Found: undefined
[10/6/2022, 10:18:45 PM] [August] [DEBUG] August Platform Config Not Set: [Undefined]
[10/6/2022, 10:18:45 PM] [August] TypeError: deviceLists.map is not a function

```

**Comment by donavanbecker** [comment]
Can you manually change your config?and just keep the following:

```
"name": "August",
            "credentials": {
                "augustId": "xxxxxxx@xxxxx.com",
                "password": "xxxxxxxxx",
                "validateCode": "xxxxxxx",
                "notice": "Keep your tokens a secret!"
            },
            "platform": "August"

```

**Comment by hrhnick** [comment]
Still hitting "TypeError: deviceLists.map is not a function"

I meant to copy what was there before, it had the debug option but also two other lines, one I believe was a MAC address.

<img width="227" alt="Screenshot 2022-10-06 at 10 52 34 PM" src="https://user-images.githubusercontent.com/223259/194458006-333b37d2-71ad-40ee-8e6d-1d29083fadc5.png">

**Comment by donavanbecker** [comment]
@hrhnick, I am adding this code ```this.errorLog(`COPY THIS LOG: ${deviceLists}`);``` into the next beta: `0.1.0-beta.26`, copy this code and paste it once you see it. Should be red.

**Comment by hrhnick** [comment]
@donavanbecker `[10/6/2022, 11:11:03 PM] [August] COPY THIS LOG: [object Object]`

**Comment by donavanbecker** [comment]
sorry about that try beta.28

**Comment by hrhnick** [comment]
Shot them to your email listed at beckersmarthome at icloud dot com

I was not sure what was sensitive/user specific regarding the keys listed and such.

**Comment by donavanbecker** [comment]
Thanks, can you give next beta a try? and let me know what happens?

**Comment by hrhnick** [comment]
New error: `10/6/2022, 11:41:33 PM] [August] TypeError: devices is not iterable `

**Comment by donavanbecker** [comment]
I am guessing you only have one lock right?

**Comment by hrhnick** [comment]
Correct. (I had the WiFi bridge accessory previously configured. But it has been unpaired and removed from my August account.)

**Comment by donavanbecker** [comment]
can you try adding in your lock id into the config? I will email you what your config should be.

**Comment by hrhnick** [comment]
Added to the config, now `[10/7/2022, 12:00:40 AM] [August] TypeError: a1.map is not a function`

**Comment by donavanbecker** [comment]
okay I think this next fix should fix it. try next beta = v0.1.0-beta.31

**Comment by hrhnick** [comment]
Same ai.map error on 31. 

Happy to try a factory reset on the lock if you think that it would help, but it does work as expected under the homebridge-august-smart-locks plugin.

**Comment by donavanbecker** [comment]
clear your config and start over.

**Comment by donavanbecker** [comment]
v1.0.4 should fix your issue.

**Comment by hrhnick** [comment]
Thanks @donavanbecker! Woke up and indeed 1.0.4 resolved the issue. You can close this out.

I will test the plug-in as well as attempt with the WiFi bridge and report back if anything comes up.
