### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by TommyGKiwi** [homebridge-plugins/homebridge-august#100]
### Describe The Bug

API default poll rate 1800s is incosistent with text 5m/360s 

### To Reproduce

change the default refresh rate

### Expected behavior

text default/value should match values

### Relevant log output

```shell
warning message is sent if you change the default refresh rate ....
code shows the inconsistency:
platform.ts
if (!this.config.options.refreshRate) {
      // default 1800 seconds (30 minutes)
      this.config.options!.refreshRate! = 1800;
      this.debugWarnLog('Using Default Refresh Rate (5 minutes).');
    } else if (this.config.options.refreshRate < 1800) {
      this.config.options.refreshRate = 1800;
      this.warnLog('Refresh Rate cannot be set to lower the 5 mins, as Lock detail (battery level, etc) are unlikely to change within that period');
    }
```

### Config for homebridge-august

```shell
"lockId": "BBA8ACA18E424FEDB6AB40AE84A0FAE1",
                        "configLockName": "Front Door",
                        "lock": {
                            "hide_contactsensor": true
                        },
                        "refreshRate": 360
```

### Screenshots

![IMG_2648](https://github.com/donavanbecker/homebridge-august/assets/46218042/76690023-6236-4c73-8f90-e642fbbfd3bd)

### Device & Model

rpi

### Node.js Version

v20.11.1 

### NPM Version

???

### Homebridge Version

v1.7.0

### Homebridge August Plugin Version

v2.0.0

### Operating System

Debian GNU/Linux Bookworm (12)

**Comment by donavanbecker** [comment]
Please try v2.1.0, if you still have an issue please open a new issue.
