### ISSUE TITLE
Feature Request: Hide specific locks

### ISSUE THREAD

**Issue by Avi0n** [homebridge-plugins/homebridge-august#14]
### Problem

I have access to several locks in different homes in my August app. I would like to be able to hide all locks except those that are mine in the Home app.

### Solution

Option to expose only certain locks to HomeKit.

**Comment by donavanbecker** [comment]
@avion540, logs displays lockIds for all locks. If you go to the config for august devices you can add those locks and check hide devices.

<a><img src="https://user-images.githubusercontent.com/9875439/194684510-4eb130db-71e3-4d25-b7fd-786d63069bb5.jpeg" width="250px"></a>

**Comment by Avi0n** [comment]
aha, thank you!
