### ISSUE TITLE
Bug: Log reports error reading properties, Home.app then reports lock "was jammed"

### ISSUE THREAD

**Issue by hrhnick** [homebridge-plugins/homebridge-august#16]
### Describe The Bug

Home.aLog reports error reading properties, Home.app then sends notification lock "was jammed"pp reports lock "was jammed" despite lock not being jammed. August app and other plugins do not report jam.

### To Reproduce

Error is random with no seeming correlation to time since lock or unlock.

### Expected behavior

No error, no Home.app notification.

### Relevant log output

```shell
[10/8/2022, 6:26:09 PM] [August] TypeError: Cannot read properties of undefined (reading 'retryCount')
[10/8/2022, 6:26:09 PM] [August] Lock: Front Door failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'retryCount')"
```

### Config for homebridge-august

```shell
"name": "August",
            "credentials": {
                "augustId": "xxxxx@xxxxxx.com",
                "password": "xxxxxx",
                "validateCode": "xxxxx",
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "August"
```

### Screenshots

 
![IMG_B63930AD8B1F-1](https://user-images.githubusercontent.com/223259/194730101-0eb9085c-efe8-4484-8928-ddbfa666e941.png)

### Device & Model

AugusAugust WiFi Smart Lock

### Node.js Version

16.17.1

### NPM Version

8.5.0

### Homebridge Version

oznu/homebridge:latest

### Homebridge August Plugin Version

4.50.1

### Homebridge Config UI X Plugin Version

1.0.4

### Operating System

Docker

**Comment by donavanbecker** [comment]
@hrhnick, currently if I get a retry count I report jammed. I think I will remove that code.

**Comment by 3ne** [comment]
Seeing the same error.

**Comment by hrhnick** [comment]
@donavanbecker could this somehow trigger the device to try unlock and relock? (To clear the jam?) 

I can’t be sure but I am pretty certain I was seeing some odd unlocks as well but couldn’t find it in the logs.

**Comment by donavanbecker** [comment]
@hrhnick @3ne, lets try v1.0.5

**Comment by 3ne** [comment]
> @hrhnick @3ne, lets try v1.0.5

Updating.

**Comment by mojodean** [comment]
From my experience, the update has cleaned up the `jam` alerts, and I'm getting normal lock/unlock alerts. I was having the same issues OP was.

**Comment by donavanbecker** [comment]
JAMMED should only happen if the API sends a false for both Locked and Unlocked.

**Comment by 3ne** [comment]
@donavanbecker all looks good ever here as well.

**Comment by donavanbecker** [comment]
Good to hear!
