### ISSUE TITLE
Feature Request: August DoorbellCam reboot

### ISSUE THREAD

**Issue by jlg89** [homebridge-plugins/homebridge-august#23]
### Problem

I have to tell you, this plugin is fantastic. It pulls DoorSense, battery status, everything. I love it. The ONE THING (isn't there always one thing?) that would be amazingly useful in an August plugin is the ability to trigger a reboot of the Doorbell Cam. It's do-able in the August Home app by drilling down to the doorbell settings and selecting the "reboot doorbell" option -- and the DC needs rebooting fairly often, especially when pulling RTSP streams into things like Scrypted or homebridge-camera-ffmpeg. It's not in the reverse-engineered API list, as hufftheweevil didn't have a Doorbell Cam for testing.

### Solution

I have a (used, clean) Doorbell Cam Pro ready to use for API scraping. I can work with someone, or send this Doorbell Cam to them.

### Alternatives

The only alternative is to use the August Home app to manually trigger a reboot, which is very...manual.

### Additional context

![IMG_0932](https://user-images.githubusercontent.com/10470394/199042188-9b31793b-b0da-45b1-a68d-867c7ca36135.jpeg)

**Comment by donavanbecker** [comment]
@jlg89, I don't think this is possible, but @hufftheweevil is the creator of the August API module that I use for this plugin. We will see what he says:

@hufftheweevil is this possible?

**Comment by hufftheweevil** [comment]
Sorry, I don't know anything about the doorbell cam.

**Comment by donavanbecker** [comment]
thanks for the response @hufftheweevil!

**Comment by jlg89** [comment]
AFAIK Nolan Brown did the initial & most comprehensive [August API scrape](https://nolanbrown.medium.com/august-lock-rest-apis-the-basics-7ec7f31e7874). Not sure who else has addressed that aspect of it.

**Comment by donavanbecker** [comment]
doesn't look like that has any info on the doorbell cam
