### ISSUE TITLE
Feature Request: Hide Lock Mechanism

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-august#26]
### Discussed in https://github.com/donavanbecker/homebridge-august/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **Phixius5968** November  2, 2022</sup>
Hi there, 
Since I have the lock added to HomeKit natively, adding it via homebridge-august double the buttons in the HomeKit. I'm actually looking for a way to hide the lock button but not the device entirely. 
My motivation is to be able to monitor the doorsense and the battery level of the lock but to simply have one lock button in the HomeKit. 

Thank you! </div>

**Comment by donavanbecker** [comment]
@Phixius5968
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-august@beta/>=1.1.0-beta.0/orange)](https://www.npmjs.com/package/homebridge-august)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-august/wiki/Beta-Version)

**Comment by Phixius5968** [comment]
Installed it. 
v 1.0.6-beta.13
Broke the plugin. Still can see to accessories but can't control anything and it doesn't get updated. Get this message on Hb Loading

[August] Discover Devices: ReferenceError: Config errors found:
Missing config.installId or AUGUST_INSTALL_ID env var

Still have my ID/Password in the config and am still validated... 

EDIT:
****removed isValidated and retried**** 

it's working, got the lock to disappear in HomeKit and HB but I can keep the door contact w/ battery % in the room the lock is installed.  
Great for that!

**Comment by Phixius5968** [comment]
However, now I have this logging : 

[11/3/2022, 8:33:41 PM] [August] Total August Locks Found: 7
[11/3/2022, 8:33:41 PM] [August] Restoring existing accessory from cache: David Lock ID: A **redacted** 9
[11/3/2022, 8:33:41 PM] [August] Restoring existing accessory from cache: Front Door Lock ID: C **redacted** 5
[11/3/2022, 8:33:41 PM] [August] Lock: Front Door Config: {"hide_lock":true,"refreshRate":300}
[11/3/2022, 8:33:41 PM] [August] Lock: Front Door Removing Lock Mechanism Service
**_[11/3/2022, 8:33:43 PM] [August] TypeError: Cannot read properties of undefined (reading 'hide_lock')
[11/3/2022, 8:33:43 PM] [August] Lock: David failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'hide_lock')"_**
[11/3/2022, 8:33:43 PM] [August] Lock: David was Unlocked
[11/3/2022, 8:33:43 PM] [August] Lock: David was Closed
[11/3/2022, 8:33:46 PM] [August] Lock: Front Door was Closed

It seems to be working just fine anyways.. 

EDIT : 

the David lock is another lock I have at the office, I like having it in this instance of HomeKit so I don't want to hide it.

**Comment by Phixius5968** [comment]
> However, now I have this logging :
> 
> [11/3/2022, 8:33:41 PM] [August] Total August Locks Found: 7 [11/3/2022, 8:33:41 PM] [August] Restoring existing accessory from cache: David Lock ID: A**redacted**9 [11/3/2022, 8:33:41 PM] [August] Restoring existing accessory from cache: Front Door Lock ID: C**redacted**5 [11/3/2022, 8:33:41 PM] [August] Lock: Front Door Config: {"hide_lock":true,"refreshRate":300} [11/3/2022, 8:33:41 PM] [August] Lock: Front Door Removing Lock Mechanism Service **_[11/3/2022, 8:33:43 PM] [August] TypeError: Cannot read properties of undefined (reading 'hide_lock') [11/3/2022, 8:33:43 PM] [August] Lock: David failed lockStatus (refreshStatus), Error Message: "Cannot read properties of undefined (reading 'hide_lock')"_** [11/3/2022, 8:33:43 PM] [August] Lock: David was Unlocked [11/3/2022, 8:33:43 PM] [August] Lock: David was Closed [11/3/2022, 8:33:46 PM] [August] Lock: Front Door was Closed
> 
> It seems to be working just fine anyways..

Fixed it : 

The workaround for it was, for every other locks I have on my account that are "hide_device": false I had to add : 
"lock": {
"hide_lock": false
},

It fixes the logging issue

**Comment by donavanbecker** [comment]
v1.1.0 has been release which resolves this.

**Comment by jmluxem** [comment]
I feel dumb not being able to figure this out; but how do I go about hiding all my locks aside from the contact sensor? Tried playing around with my config file but no go so far...

**Comment by donavanbecker** [comment]
> I feel dumb not being able to figure this out; but how do I go about hiding all my locks aside from the contact sensor? Tried playing around with my config file but no go so far...

In Homebridge, you can get the deviceid from the plugins settings > devices tab. You will then copy that deviceId and go to the settings tab to and input it into the deviceId field. From there you will get config options.

**Comment by jmluxem** [comment]
> > I feel dumb not being able to figure this out; but how do I go about hiding all my locks aside from the contact sensor? Tried playing around with my config file but no go so far...
> 
> In Homebridge, you can get the deviceid from the plugins settings > devices tab. You will then copy that deviceId and go to the settings tab to and input it into the deviceId field. From there you will get config options.

Awesome - that did it, thank you! I didn't realize that was a placeholder value in that DeviceID field. Thanks for the quick reply!
