### ISSUE TITLE
August Lock Plug-in Error

### ISSUE THREAD

**Issue by Geebs11** [homebridge-plugins/homebridge-august#28]
### Describe Your Problem

Hello, I am trying to an August WiFi lock via Homebridge, and have installed your August Plugin and after trying various Node.js versions (14.18.0 suggested didn't work but the Homebridge Logs stated than I needed 14.20.1 which got me closer. Now I have one remaining Error message:

### Relevant log output

```shell
[August] Discover Devices: TypeError: Cannot convert undefined or null to object
```

### Config for homebridge-august

```shell
{
    "name": "August",
    "credentials": {
        "augustId": "****.***@icloud.com",
        "password": "***@*********",
        "validateCode": "******",
        "notice": "Keep your tokens a secret!"
    },
    "platform": "August"
}
```

### Device & Model

August WiFi Lock

### Node.js Version

v14.20.1

### NPM Version

V6.14.17

### Homebridge Version

v1.5.1

### Homebridge August Plugin Version

v1.0.5

### Operating System

macOS Ventura

**Comment by evantobin** [comment]
This error occurs when saving the config via the UI. The august-api library is expecting the verification code as a number not a string. Edit the config manually to fix this. I'll send a pull request to fix

**Comment by donavanbecker** [comment]
Thanks @evantobin! Sorry I have been busy. I will merge into a beta release and then release a new version once tested.

**Comment by donavanbecker** [comment]
@evantobin @Geebs11, Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-august@beta/>=1.0.6-beta.20/orange)](https://www.npmjs.com/package/homebridge-august)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-august/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
v1.1.0 has been release which should resolve this.

**Comment by ctaylora1231** [comment]
I’m still having this issue
