### ISSUE TITLE
Bug: MFA Code bug and UX inconsistency 

### ISSUE THREAD

**Issue by bveiseh** [homebridge-plugins/homebridge-august#33]
### Describe The Bug

After inputting email and password, hitting save, and receiving the MFA Auth key via email, going back to the config page to enter it works, but when I hit save, it just sends me another code, thereby invalidating the previous one.

### To Reproduce

Followed instructions in readme

### Expected behavior

it should have accepted the code and then brought up my lock when I scan the QR

### Relevant log output

```shell
n/a
```

### Config for homebridge-august

```shell
it was the standard initial json, with the addition of my credentials, nothing else
```

### Device & Model

RPI4

### Node.js Version

latest

### NPM Version

latest

### Homebridge Version

latest

### Homebridge August Plugin Version

latest

### Homebridge Config UI X Plugin Version

latest

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
please update your info with exact info, not `latest`. Also are you on HOOBS or Homebridge?
