### ISSUE TITLE
Discover Devices: ReferenceError: Config errors found: Missing config.installId or AUGUST_INSTALL_ID env var

### ISSUE THREAD

**Issue by ghost** [homebridge-plugins/homebridge-august#44]
### Describe Your Problem

Homebridge providing log error on startup.

### Relevant log output

```shell
Discover Devices: ReferenceError: Config errors found:
Missing config.installId or AUGUST_INSTALL_ID env var
```

### Config for homebridge-august

```shell
{
            "name": "August",
            "credentials": {
                "augustId": "xxxxxxxxxxxxx",
                "password": "xxxxxxxxxxxxx",
                "notice": "Keep your tokens a secret!",
                "isValidated": true
            },
            "options": {
                "devices": [
                    {
                        "lockId": "xxxxxxxxxxxxxx",
                        "configLockName": "Front Door",
                        "hide_device": false,
                        "lock": {
                            "hide_lock": true
                        }
                    }
                ]
            },
            "platform": "August"
        }
```

### Device & Model

Raspberry Pi 3B

### Node.js Version

v18.12.1

### NPM Version

v8.19.2

### Homebridge Version

v1.6.0

### Homebridge August Plugin Version

v1.1.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Remove `isValidated` config and try again

**Comment by josmanvis** [comment]
> Remove `isValidated` config and try again

this does not seem to solve this issue for me. how bout you @michaelroon ?

**Comment by donavanbecker** [comment]
@josmanvis You get the same logs?

**Comment by jlg89** [comment]
I'm still getting the error, along with a homebridge version complaint. This is on an install that had been working for at least a couple months with no issues. The issue started maybe mid or late December, seemed to roughly coincide with one of the iOS 16 updates. 

```

1/20/2023, 3:32:49 PMDoor Access BridgeERROR[31mThe plugin "homebridge-august" requires a Homebridge version of ^1.6.0 || ^2.0.0-beta.0 which does not satisfy the current Homebridge version of 1.5.0. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
1/20/2023, 3:32:50 PMDoor Access BridgeLoaded plugin 'homebridge-august'
1/20/2023, 3:32:50 PMDoor Access BridgeLoading 1 platforms...
1/20/2023, 3:32:50 PMDoor Access BridgeAugustERRORDiscover Devices: ReferenceError: Config errors found: Missing config.installId or AUGUST_INSTALL_ID env var
```

**Comment by donavanbecker** [comment]
@michaelroon were you able to get this resolved?

**Comment by jlg89** [comment]
Gave one more shot at removing the isValidated config line etc., and it worked this time. Not sure what made the difference, but for future reference (because I will forget):

1. Remove both the validateCode and isValidated lines from the config.
2. Restart the bridge.
3. Get the new validateCode from your email (e.g. 123456)
4. Add `"validateCode": "123456",` to the config.
5. Restart the bridge.

The plugin will automatically add the isValidated line, don't add it yourself. Adding it yourself probably breaks the process (not sure if this is what I or anyone else was doing, but it's possible).
