### ISSUE TITLE
Bug: 2FA code for mobile phone never arrives

### ISSUE THREAD

**Issue by mattheworiordan** [homebridge-plugins/homebridge-august#46]
### Describe The Bug

After entering phone number and password, I am told to check for the auth code but it never arrives

### To Reproduce

Install plugin, enter phone number + password, restart Homebridge, see log stating "Check +447930XXXXXX for your validation code"

### Expected behavior

Auth code is sent

### Relevant log output

After rebooting Homebridge, this is what I see:

```shell
[18/01/2023, 16:45:09] [August] Input Your August email verification code into the validateCode config and restart Homebridge.
[18/01/2023, 16:45:09] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge C193) is running on port 51867.
FetchError: Status 403 (undefined): undefined
Check +447930XXXXXX for your validation code
```

Note I obfuscated the complete phone number with XXXXXX.

--

Note: I have tried with email and password instead of phone number and password. It seems to start off better, after entering email & password in the augustId and password field I see this in the logs:

```
[18/01/2023, 16:57:10] [August] Input Your August email verification code into the validateCode config and restart Homebridge.
[18/01/2023, 16:57:10] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge C193) is running on port 51867.
Check matt@XXXX.XXXXX for your validation code
```

I then receive an email with the following from August "Your August email verification code is XXXXXX"

I enter that code into the August plugin and restart Homebridge, and then get this in the logs:

```
FetchError: Status 401 (undefined): undefined
[18/01/2023, 16:58:13] [August] Discover Devices: TypeError: Cannot convert undefined or null to object
```

When I then look at my config I see that `isValidated` is true:

```shell
       {
            "name": "August",
            "credentials": {
                "augustId": "matt@XXX.XXX",
                "password": "XXXXXXX",
                "installId": "0f8ef282-9381-4a6b-8a86-XXXXXXXXXX",
                "notice": "Keep your tokens a secret!",
                "isValidated": true
            },
            "platform": "August"
        }
```

### Config for homebridge-august

```shell
{
    "bridge": {
        "name": "Homebridge C193",
        "username": "XXXXXX",
        "port": 51867,
        "pin": "XXX-XXX-XXX",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Meross",
            "username": "matt@XXXX.XXX",
            "password": "XXXXXXXX",
            "connection": "default",
            "platform": "Meross"
        },
        {
            "name": "August",
            "credentials": {
                "augustId": "+447930XXXXXX",
                "password": "XXXXXXXX",
                "notice": "Keep your tokens a secret!",
                "installId": "0f8ef282-9381-4a6b-8a86-XXXXXXXXX"
            },
            "platform": "August"
        }
    ]
}
```

### Device & Model

Raspberry Pi with Homebridge image

### Node.js Version

v18.12.1

### NPM Version

Unknown

### Homebridge Version

 Up To Date v1.6.0

### Homebridge August Plugin Version

v1.1.0

### Homebridge Config UI X Plugin Version

v4.50.2

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by donavanbecker** [comment]
Nothing I can really do about a text message not being sent.

**Comment by mattheworiordan** [comment]
> Nothing I can really do about a text message not being sent.

I would agree if I was confident the issue is because August are not sending it. When I use SMS auth with August direcrtly, I do get text messages.  Anyway, you can close this issue if you want, I got it working with email in the end as I had to give up on text auth via this plugin. Thanks for your work on this plugin btw.
