### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by grahambeale** [homebridge-plugins/homebridge-august#50]
### Describe Your Problem

Persistent ’unlocking…’ state on Conexis L1 via Yale Connect Bridge

### Screenshots

![C05C05A6-DD1B-4AD8-8463-4944676081D3](https://user-images.githubusercontent.com/1138262/216298139-f66edb9c-c63c-4dc8-9e4c-9b1a7e4b1509.png)
![15C667B9-038A-4AE0-9300-86E70F1BAE1F](https://user-images.githubusercontent.com/1138262/216298148-608ff378-3736-4d6d-bc1d-999a017ba0f7.png)
![555B1922-EB33-4417-A772-37FD264A0DEC](https://user-images.githubusercontent.com/1138262/216298156-49d295f4-79c6-4c26-853d-dd5e2123f181.png)

### Device & Model

Raspberry Pi 

### Node.js Version

16.15.0

### NPM Version

Unsure

### Homebridge Version

1.6.0

### Homebridge August Plugin Version

1.1.10

### Homebridge Config UI X Plugin Version

4.50.2

### Operating System

Raspberry Pi

**Comment by grahambeale** [comment]
Btw, just want to say a huge thank for this plug-in. It’s literally the only thing I can find to bring my Yale lock to HomeKit

**Comment by grahambeale** [comment]
For context this is what I am using with my Yale Conexis L1 lock https://yalehome.co.uk/yale-access-connect-kit/

**Comment by matclothier** [comment]
I get this same issue on both my keyless connected and Conexis L1. I am using the same yale access connect kit as you.
