### ISSUE TITLE
Bug: if validation code starts with zero it fails

### ISSUE THREAD

**Issue by gopi-ar** [homebridge-plugins/homebridge-august#54]
### Describe The Bug

if validation code starts with zero it fails with "if validation code starts with zero it fails"

### To Reproduce

Assume Yale / August sends a code starting with 0

### Expected behavior

It should wrap the 0 in quotes probably?

### Relevant log output

```shell
[August] Validated Error: Error: Validation code is invalid, should be six digits
```

### Config for homebridge-august

```shell
Default
```

### Screenshots

Removing the install ID and redoing auth where I got a different code from Yale fixed this.

Also, you can add compatibility in your repo to say it works with:
YDR 414a
YDR 50GA

and the Yale Access App.

### Device & Model

Yale

### Node.js Version

Node.js v18.15.0

### NPM Version

x

### Homebridge Version

x

### Homebridge August Plugin Version

1.1.0

### Homebridge Config UI X Plugin Version

4.5

### Operating System

Ubuntu

**Comment by donavanbecker** [comment]
@gopi-ar Can you submit a PR?

**Comment by jlg89** [comment]
Same as https://github.com/donavanbecker/homebridge-august/issues/48
