### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by pete8314** [homebridge-plugins/homebridge-august#56]
### Describe Your Problem

August Plugin not triggering 2FA request

### Relevant log output

```shell
Hi - no matter what I do, I cannot get the plugin to generate the request for the 2FA code.

I've tried doing it myself (i.e. logging into August via web client, requesting the code, and entering that into the plugin UI/restarting etc), but no joy.

I don't think it's related, but August seems to have 2 authentication sites:

https://account.august.com/login
https://auth.august.com/

The second site will generate a 2FA code, but then fails to login and leads to a 404 error. The first site works as expected (but the 2FA code it generates doesn't seem to work for the plugin).
```

### Config for homebridge-august

```shell
{
            "name": "August",
            "credentials": {
                "augustId": "pete@abstractocean.com",
                "password": "<redacted>",
                "installId": "e57cdcbd-7af5-4da4-b014-d60237d01d60",
                "isValidated": false,
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "logging": "debug"
            },
            "platform": "August"
        }
    ]
}
```

### Device & Model

n/a

### Node.js Version

18.16.0

### NPM Version

??

### Homebridge Version

1.6.0

### Homebridge August Plugin Version

1.1.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Have you tried clearing your config and setting up again?

**Comment by pete8314** [comment]
yes, a few times. Tried the beta release too.

**Comment by donavanbecker** [comment]
I see you didn't fill in the Config-UI-X version, by chance are you using HOOBs?

**Comment by pete8314** [comment]
I'm not, just a straight-up Homebridge running on a Pi. Just 6 plugins (incl. this one), so nothing too strenuous for it. I've had a ticket open with August as well, about why auth.august.com is leading to a 404, I'm 6 replies in with them, I can't tell you how awful their support is.

**Comment by pete8314** [comment]
Follow-up from the great August support, they've finally confirmed that auth.august.com is no longer functional (although it's there, and there's no redirect or warning to suggest otherwise), and only account.august.com can be used for web login. Again, not sure this has a bearing on this issue, but it might...

**Comment by donavanbecker** [comment]
URL this plugin is using: https://github.com/hufftheweevil/august-api/blob/ffcf2c51f0a8aedb86aa69c4d3a8412525eb1c56/src/index.js#L14
