### ISSUE TITLE
Support Request:Discover Devices Issue

### ISSUE THREAD

**Issue by simonrb2000** [homebridge-plugins/homebridge-august#57]
### Describe Your Problem

It appears the plug-in is unable to grab my locks. Logs in ok and I get the code from August 

### Config for homebridge-august

```shell
"name": "August",
            "credentials": {
                "augustId": "xxxx",
                "password": "xxxx",
                "installId": "xxxxx",
                "notice": "Keep your tokens a secret!",
                "isValidated": true
            },
            "platform": "August",
            "_bridge": {
                "username": "0E:E3:99:81:xx:xx",
                "port": xxxxx
            }
        }
```

### Screenshots

/
![IMG_2075](https://user-images.githubusercontent.com/15991296/235295677-a57372ae-79a4-4060-a39e-84c3d05e492c.jpeg)

### Device & Model

Raspberry pi 

### Node.js Version

V18

### NPM Version

V

### Homebridge Version

V1.6

### Homebridge August Plugin Version

Beta

### Homebridge Config UI X Plugin Version

Latest

### Operating System

Bullseye

**Comment by kanglu** [comment]
I got a similar error. Here is the entire stack trace:

TypeError: Cannot read properties of undefined (reading 'x-august-access-token')
    at August.session (/usr/local/lib/node_modules/homebridge-august/node_modules/august-api/src/util/session.js:28:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at August.#start (/usr/local/lib/node_modules/homebridge-august/node_modules/august-api/src/index.js:43:19)
    at August.authorize (/usr/local/lib/node_modules/homebridge-august/node_modules/august-api/src/methods/authorize.js:9:13)

It looks the 429 fetch error is the "Too Many Requests".

I guess I will wait a few hours and try again.

**Comment by simonrb2000** [comment]
Are you on Virgin Media by any chance? 

Only reason I asked is I’ve recently been having issues while on Wi-Fi and can’t use the Yale app, if I turn off Wi-Fi then it works. 

After your comment about 429 error (which is what comes up for me using the Yale app on Wi-Fi) I connected my router to a VPN and now the locks show and operate in HomeKit but I still have the same errors within Homebridge. 

Odd.

**Comment by danieljcooper** [comment]
Same issue here also.

I am on Virgin Media but the Yale app seems to be fine. Just Homebridge that has the error.

**Comment by simonrb2000** [comment]
You’re not getting 429 error? Lucky you, it is rather frustrating. Are you using the Yale Home app?




On 1 May 2023, at 20:55, danieljcooper ***@***.***> wrote:

﻿

Same issue here also.

I am on Virgin Media but the Yale app seems to be fine. Just Homebridge that has the error.

**Comment by kanglu** [comment]
I did retry after a few hours and it worked. Everything is fine now.
