### ISSUE TITLE
Feature Request: Reduce the number of calls to the August API.

### ISSUE THREAD

**Issue by dacarson** [homebridge-plugins/homebridge-august#67]
### Problem

Every time the status of the lock is requested, two calls are made to the August API. I see homebridge-august making these calls to august-api when it refreshes the [state of the lock](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L216): 
[lockStatus](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L220): 
`const lockStatus = await this.platform.august.status(this.device.lockId);` 
which calls through to the august-api status object, which then does this: 
`let { body } = await this.put(`/remoteoperate/${lockId}/status`)` 
and [lockDetails](https://github.com/donavanbecker/homebridge-august/blob/8d3fa90c233b7f9cf43a9996805254d28dc3cff2/src/devices/lock.ts#L239): 
`const lockDetails = await this.platform.august.details(this.device.lockId);` 
which calls through to august-api details object, which then does this: 
`let { body } = await this.get(`/locks/${lockId}`)`

### Solution

Almost all the data is available in the lockDetails call, except for if the lock is jammed (retryCount > 1). We should just use lockDetails and work out another way to handle a jammed lock.

### Additional context

Calls to the August API is rate limited, so reducing the number of calls to the API is a good thing in general. Also some people are running into issues when they have multiple locks, they hit the rate limit.

**Comment by donavanbecker** [comment]
Thanks for the fix!

**Comment by donavanbecker** [comment]
v1.2.0 has been released
