### ISSUE TITLE
Bug:With debugging turned on, the full JSON object of the AugustEvent isn't printed

### ISSUE THREAD

**Issue by dacarson** [homebridge-plugins/homebridge-august#68]
### Describe The Bug

It is difficult to debug what is going on when the AugustEvent is printed to the console.

### To Reproduce

Turn on debugging, and observe August Event log entry

### Expected behavior

The full JSON AugustEvent is printed.

### Relevant log output

```shell
[7/26/2023, 1:27:01 PM] [August] [DEBUG] Lock: Garage Door AugustEvent: "16904032209277141"
```

### Config for homebridge-august

```shell
N/A for this issue
```

### Device & Model

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Homebridge Version

N/A

### Homebridge August Plugin Version

v1.2.0-beta.2

### Homebridge Config UI X Plugin Version

N/A

### Operating System

N/A

**Comment by donavanbecker** [comment]
Thanks for the fix!

**Comment by donavanbecker** [comment]
v1.2.0 has been released
