### ISSUE TITLE
Country Codes?

### ISSUE THREAD

**Issue by Jarvichi** [homebridge-plugins/homebridge-august#85]
### Describe Your Problem

I live in the UK, I’ve set the country code to “UK”, everything seems to work (ish) the logs contain repeated “[August] Country code: UK”. Is this correct? I ask because I’m trying to see the logs for another issue I have, want to make sure everything is set up correctly before I try to work out the other problems I’m seeing.
I looked at the API and couldn’t work out what is expected when it comes to country codes, I’ve also tried the +44 (international dialling code) to see if that works, but I see the same log. Any ideas or suggestions would be appreciated.

As for the problem in having, I get notifications from HomeKit periodically telling me that the door is locked/unlocked (when the state hasn’t changed) is the August plugin triggering those alerts? If so should it only trigger an alert when the state changes from locked to unlocked (and vice versa)? 

Looking closer at the Home App I can see the lock reports “Unknown” and then the actual status, so I’m guessing it’s the “actual state” > “unknown state” > “actual state” transition that triggers the alert, any suggestions on why I might be getting and unknown state report periodically would be appreciated (especially if it’s the country code that’s wrong).

### Config for homebridge-august

```shell
"name": "August",
            "credentials": {
                "augustId": "email@email.com",
                "password": "password",
                "countryCode": "UK",
                "installId": "uuid",
                "isValidated": true,
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "refreshRate": 360,
                "pushRate": 5,
                "logging": "standard"
            },
```

### Screenshots

![IMG_9493](https://github.com/donavanbecker/homebridge-august/assets/9568432/0684ce36-624c-47f3-866f-d1da5e1f7347)

### Device & Model

Yale Conexis with Yale Connect Bridge

### Node.js Version

v20.10.0

### NPM Version

10.2.3

### Homebridge Version

V1.7.0

### Homebridge August Plugin Version

V1.3.3

### Homebridge Config UI X Plugin Version

V4.54.1

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
This isn't an issue just logging that needs to be corrected which is corrected in the beta branch.
