### ISSUE TITLE
Feature Request: List of unsupported devices

### ISSUE THREAD

**Issue by itsnathanlam** [homebridge-plugins/homebridge-august#87]
### Problem

Unclear if support for certain devices have yet to be considered or not possible at all. For example August Smart Lock 3rd Generation (not pro) with Connect Hub

### Solution

List of unsupported devices for example August Smart Lock 3rd Generation (not pro) with Connect Hub

**Comment by donavanbecker** [comment]
I believe that version should work. I will not be create an unsupported and supported list. If someone submits a PR for a supported device, I will add it to my supported list. Thanks
